---
apiVersion: v1
kind: Service
metadata:
  name: udp-port
  namespace: teamspeak
spec:
  type: NodePort
  ports:
    - port: 9987
      targetPort: 9987
      protocol: UDP
      nodePort: 30888
  selector:
    app: teamspeak
---
apiVersion: v1
kind: Service
metadata:
  name: next-port
  namespace: teamspeak
spec:
  type: ClusterIP
  ports:
    - port: 10011
      targetPort: 10011
  selector:
    app: teamspeak
---
apiVersion: v1
kind: Service
metadata:
  name: next-next-port
  namespace: teamspeak
spec:
  type: ClusterIP
  ports:
    - port: 30033
      targetPort: 30033
  selector:
    app: teamspeak
