---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv0005-teamspeak
  namespace: teamspeak
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: pv0005-teamspeak
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /nfsshare/pv0005/teamspeak
    server: 192.168.1.195
